apiVersion: v1
kind: ConfigMap
metadata:
  name: typesense-scraper-configmap-procyon-vip
  namespace: kube-system
  labels:
    domain: procyon-vip
data:
  typesense-scraper.json: |-
    {
      "index_name": "faq",
      "start_urls": [
        {
          "url": "https://www.procyon.vip/ja-JP",
          "tags": ["ja-JP", "index"]
        },
        {
          "url": "https://www.procyon.vip/ja-JP/faq?topic=Login",
          "selectors_key": "login",
          "tags": ["ja-JP", "login"]
        },
        {
          "url": "https://www.procyon.vip/ja-JP/faq?topic=AccountSettings",
          "selectors_key": "accountsettings",
          "tags": ["ja-JP", "accountsettings"]
        },
        {
          "url": "https://www.procyon.vip/ja-JP/faq?topic=Dashboard",
          "selectors_key": "dashboard",
          "tags": ["ja-JP", "dashboard"]
        },
        {
          "url": "https://www.procyon.vip/ja-JP/faq?topic=Transactions",
          "selectors_key": "transaction",
          "tags": ["ja-JP", "transaction"]
        },
        {
          "url": "https://www.procyon.vip/ja-JP/faq?topic=KYC",
          "selectors_key": "kyc",
          "tags": ["ja-JP", "kyc"]
        },
        {
          "url": "https://www.procyon.vip/ja-JP/faq?topic=Security",
          "selectors_key": "security",
          "tags": ["ja-JP", "security"]
        },
        {
          "url": "https://www.procyon.vip/ja-JP/faq?topic=General",
          "selectors_key": "general",
          "tags": ["ja-JP", "general"]
        },
        {
          "url": "https://www.procyon.vip/ja-JP/faq?topic=Aleo",
          "selectors_key": "aleo",
          "tags": ["ja-JP", "aleo"]
        },
        {
          "url": "https://www.procyon.vip/ja-JP/faq?topic=IronFish",
          "selectors_key": "ironfish",
          "tags": ["ja-JP", "ironfish"]
        },
        {
          "url": "https://www.procyon.vip/ja-JP/faq?topic=Spacemesh",
          "selectors_key": "spacemesh",
          "tags": ["ja-JP", "spacemesh"]
        },
        {
          "url": "https://www.procyon.vip/en-US",
          "tags": ["en-US", "index"]
        },
        {
          "url": "https://www.procyon.vip/en-US/faq?topic=Login",
          "selectors_key": "login",
          "tags": ["en-US", "login"]
        },
        {
          "url": "https://www.procyon.vip/en-US/faq?topic=AccountSettings",
          "selectors_key": "accountsettings",
          "tags": ["en-US", "accountsettings"]
        },
        {
          "url": "https://www.procyon.vip/en-US/faq?topic=Dashboard",
          "selectors_key": "dashboard",
          "tags": ["en-US", "dashboard"]
        },
        {
          "url": "https://www.procyon.vip/en-US/faq?topic=Transactions",
          "selectors_key": "transaction",
          "tags": ["en-US", "transaction"]
        },
        {
          "url": "https://www.procyon.vip/en-US/faq?topic=KYC",
          "selectors_key": "kyc",
          "tags": ["en-US", "kyc"]
        },
        {
          "url": "https://www.procyon.vip/en-US/faq?topic=Security",
          "selectors_key": "security",
          "tags": ["en-US", "security"]
        },
        {
          "url": "https://www.procyon.vip/en-US/faq?topic=General",
          "selectors_key": "general",
          "tags": ["en-US", "general"]
        },
        {
          "url": "https://www.procyon.vip/en-US/faq?topic=Aleo",
          "selectors_key": "aleo",
          "tags": ["en-US", "aleo"]
        },
        {
          "url": "https://www.procyon.vip/en-US/faq?topic=IronFish",
          "selectors_key": "ironfish",
          "tags": ["en-US", "ironfish"]
        },
        {
          "url": "https://www.procyon.vip/en-US/faq?topic=Spacemesh",
          "selectors_key": "spacemesh",
          "tags": ["en-US", "spacemesh"]
        }
      ],
      "selectors": {
        "default": {
          "lvl0": ".content.faq h2",
          "lvl1": ".faq-content-main h3",
          "text": ".faq-content-main h4, .faq-content-main ul li, .faq-content-main p"
        }
      },
      "selectors_exclude": [
        "#support"
      ],
      "js_render": true,
      "js_wait": 5
    }
---
apiVersion: batch/v1
kind: Job
metadata:
  name: typesense-scraper-job-procyon-vip
  namespace: kube-system
  labels:
    domain: procyon-vip
spec:
  ttlSecondsAfterFinished: 10
  parallelism: 1
  template:
    spec:
      containers:
      - name: scraper
        image: typesense/docsearch-scraper:0.7.0
        env:
        - name: CONFIG
          value: /tmp/search/typesense-scraper.json
        - name: TYPESENSE_HOST
          value: typesense-svc
        - name: TYPESENSE_PORT
          value: "8108"
        - name: TYPESENSE_PROTOCOL
          value: http
        - name: UPDATE_NB_HITS
          value: 'false'
        - name: TYPESENSE_API_KEY
          valueFrom:
            configMapKeyRef:
              name: typesense-configmap
              key: apikey
        volumeMounts:
        - name: config
          mountPath: /tmp/search
        - name: shm
          mountPath: /dev/shm
      restartPolicy: Never
      volumes:
      - name: config
        configMap:
          name: typesense-scraper-configmap-procyon-vip
      - name: shm
        hostPath:
          path: /dev/shm
