<template>
  <Page>
    <template #body>
      <h2>Aleo Overview</h2>
      <div class='faq-content'>
        <div class='faq-content-nav'>
          <h3>Navigation</h3>

          <ul class='faq-nav-links'>
            <li><a @click='scrollTo("Aleo Mining")'>Aleo Mining</a></li>
            <li><a @click='scrollTo("About Aleo")'>About Aleo</a></li>
            <li><a @click='scrollTo("Aleo Technology")'>Aleo Technology</a></li>
            <li><a @click='scrollTo("Why did Procyon choose Aleo?")'>Why did procyon choose Aleo?</a></li>
          </ul>

          <div class='hr' />
        </div>

        <div class='faq-content-main'>
          <h3 id='Aleo Mining'>
            Aleo Mining
          </h3>
          <h4>Product Details</h4>
          <p>
            <strong>Start of Mining: </strong>At the launch of the mainnet
            <a href='https://www.aleo.org/post/incentivized-testnet-retrospective' target='_blank'>
              (scheduled for October 2022)
            </a>
          </p>
          <p><strong>Mining Period: </strong>365 days (after mainnet launch)</p>
          <p><strong>Technical Service Fee: </strong>20%</p>
          <p>
            <strong>Mining Algorithms: </strong>In order to optimally increase the mining machines' hash power,
            a large number of GPUs are integrated into a single mining machine. Due to to this, Procyon has
            decided to divide the hash power generated by 1 machine into 100 units.
          </p>

          <h3 id='About Aleo'>
            About Aleo
          </h3>
          <h4>What is Aleo?</h4>
          <p>
            A Layer 1 Crypto project developed and operated by Aleo Systems Inc focusing on Web3 privacy and
            offering a solution to various issues of traditional blockchains.
          </p>

          <h4>Aleo Company Profile</h4>

          <ul>
            <li><strong>Company Name: </strong>Aleo Systems Inc.</li>
            <li><strong>Location: </strong>Reno, Nevada, United States</li>
            <li><strong>Founded: </strong>2019</li>
            <li><strong>Start of Testnet 1: </strong>Q1, 2021</li>
            <li><strong>Start of Testnet 2: </strong>December 6, 2021</li>
            <li><strong>Mainnet Launch: </strong>October, 2022 (tentative schedule by Aleo Official)</li>
            <a href='https://www.aleo.org/post/aleo-token-economics' target='_blank'>Aleo Token Economics</a>
          </ul>

          <h3>Co-Founders of Aleo</h3>

          <h4>Howard Hu</h4>

          <p>
            A former engineer at Google after graduating from UC Berkeley. Worked in Blockchain at Berkeley
            (a blockchain accelerator at Berkeley University) and Dekrypt Capital for over 10 years.
          </p>

          <h4>Collin Chin</h4>

          <p>
            Interned as a smart contract developer at ConsenSys while at Berkeley. Worked as a technical advisor
            and security consultant at Blockchain at Berkeley and Argus.
          </p>

          <h4>Raymond Chu</h4>

          <p>
            While at Berkeley, interned as an engineer at IBM and Amazon. After graduation, worked as a project
            manager and security consultant at Blockchain at Berkeley and Argus.
          </p>

          <h4>Michael Beller</h4>

          <p>Senior Manager at Accenture for 7 years. Served as COO/CIO in numerous IT/financial startups.</p>

          <h3 id='Aleo Technology'>
            Aleo Technology
          </h3>

          <h4>Aleo is the first platform to offer fully private applications.</h4>

          <p>
            Aleo achieves privacy by leveraging decentralized systems and zero-knowledge cryptography to
            protect user data on the web. Using zero-knowledge cryptography, Aleo moves smart contract
            execution off-chain to enable a diverse range of decentralized applications that are both
            entirely private and can scale to tens of thousands of transactions per second. Built on an
            open, public blockchain, Aleo brings all the flexibility of Ethereum but with a more scalable
            architecture in which miners don’t need to re-run every transaction, but simply verify their correctness.
          </p>

          <h3 id='Why did Procyon choose Aleo?'>
            Why did Procyon choose Aleo?
          </h3>

          <p>
            In terms of VC investments Aleo somewhat similar to Filecoin. The total funding for Filecoin is $257 million,\
            while the total funding of Aleo is $228 million.
          </p>

          <p>Aleo's team is highly qualified and has a comprehensive strategy on how the service will be delivered to customers.</p>

          <p>
            On the technical side, Aleo offers one of the most important infrastructures of Web3’s future with its zero-knowledge
            proof – using ZKPs to achieve both privacy and programmability.
          </p>

          <p>
            In terms of Aleo's future ecosystem, Aleo has the potential to be the next Ethereum or Solana through its Layer 1 technology.
            Various applications will be developed on top of Aleo, as we have already seen with the strategic partnership with
            Forte - the gaming company. Aleo aims to become the solution to Web2's major drawbacks such as data leaks, private
            data monetization, and the permanent availability of leaked data.
          </p>

          <div class='hr' />
        </div>
      </div>
    </template>
  </Page>
</template>

<script setup lang='ts'>
import { defineAsyncComponent } from 'vue'
import { scrollTo } from 'src/utils/scroll'

const Page = defineAsyncComponent(() => import('src/pages/faq/Page.vue'))

</script>
